# Initializing different types of arrays

## Zero and One array

In [1]:
import numpy as np

In [2]:
# All zero array
np.zeros((2, 3, 4), dtype="int16")

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [3]:
# All ones matrix
np.ones((4, 3), dtype="float64")  # float64 is default dtype of numpy

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [5]:
# Using full like
a = np.array([1, 3, 6])
np.full_like(a, 10)  # creates array of shape a

# Or use full with a.shape as argument

array([10, 10, 10])

## Random number array

In [6]:
# Random numbers
# Don't think too much about memorisation
# Just remember what's possible and then google it

# high, low, shape, dtype
np.random.randint(-100, 100, (4, 5), dtype="int16")

array([[-60,  97,  -7, -74, -68],
       [ 74,   9, -81, -54,  41],
       [ 16,  55,  11,  63,  18],
       [ 27, -68, -61,   8,  51]], dtype=int16)

In [7]:
np.random.rand(2, 3, 4)

array([[[0.35851007, 0.99070296, 0.45220983, 0.81361196],
        [0.33394063, 0.99831955, 0.93065032, 0.3387639 ],
        [0.15711312, 0.57448644, 0.23744624, 0.34115052]],

       [[0.85338376, 0.72161479, 0.07943825, 0.489413  ],
        [0.73051294, 0.76997481, 0.95651517, 0.89725635],
        [0.71630354, 0.97914802, 0.22202004, 0.75430827]]])

## Identity Matrix

In [8]:
# Identity matrix
np.identity(5, dtype="int32")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

## Repeat existing array
Don't think too much! just google stuff

In [9]:
# Repeat an existing array
a = np.array([1, 3, 6])
print(np.repeat(a, 3, axis=0))

# You need a to be a 2D array to repeat it in 2D
print(np.repeat([a], 3, axis=0))

# or
a = np.reshape(a, (1, -1))
print(np.repeat(a, 3, axis=0))

[1 1 1 3 3 3 6 6 6]
[[1 3 6]
 [1 3 6]
 [1 3 6]]
[[1 3 6]
 [1 3 6]
 [1 3 6]]


# Example Question

In [10]:
# Example: initialize the following array
# [[1, 1, 1, 1, 1],
#  [1, 0, 0, 0, 1],
#  [1, 0, 9, 0, 1],
#  [1, 0, 0, 0, 1],
#  [1, 1, 1, 1, 1]]

arr = np.ones((5, 5), dtype="int16")
arr[1:-1, 1:-1] = np.zeros((3, 3))
arr[2, 2] = 9
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

##### Be careful when copying arrays!!!

In [11]:
a = np.array([1, 2, 3])
b = a
b[0] = 100

print(a)

a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100

print(a)

[100   2   3]
[1 2 3]


## Arange in numpy (alternative to python range)

In [12]:
x = range(5)
x

range(0, 5)

In [13]:
x = np.arange(0, 10, 2)
x

array([0, 2, 4, 6, 8])