In [1]:
import numpy as np

## Accessing and changing 
- elements
- rows
- columns 

In [2]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a.shape

(2, 7)

### Access an element

In [3]:
# get a specific element [row, column]
print(a[1, 5])
a[1, -2]

13


13

### Access rows and columns

In [4]:
# get a specific row and column
a[0, :]  # row
a[:, 2]  # column

array([ 3, 10])

### Fancy slicing

In [5]:
# getting fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [6]:
# changing elements and rows and columns

# change entire row
a[0, :] = [20, 21, 22, 23, 24, 25, 26]

# change entire column
a[:, 0] = 100
# note that if we give it a single value (not an array of appropriate size), all elements are set to tht particular value

a[1, 5] = 1000  # change element
a

array([[ 100,   21,   22,   23,   24,   25,   26],
       [ 100,    9,   10,   11,   12, 1000,   14]])

### 3D - example

In [7]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [8]:
# Get specific element - work outside in
b[1, 0, 1]

6

In [9]:
# Replace in 3D
b[:, 1, :] = [[10, 20], [30, 40]]
b

array([[[ 1,  2],
        [10, 20]],

       [[ 5,  6],
        [30, 40]]])