### Initializing different types of arrays

In [97]:
import numpy as np

In [98]:
# All zero array
np.zeros((2, 3, 4), dtype="int16")

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [99]:
# All ones matrix
np.ones((4, 3), dtype="float64")  # float64 is default dtype of numpy

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [100]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [101]:
# Using full like
a = np.array([1, 3, 6])
np.full_like(a, 10)  # creates array of shape a

# Or use full with a.shape as argument

array([10, 10, 10])

In [102]:
# Random numbers
# Don't think too much about memorisation
# Just remember what's possible and then google it
np.random.rand(2, 2, 3)

array([[[0.33534439, 0.38792993, 0.21098575],
        [0.25315268, 0.21819783, 0.04668452]],

       [[0.20969303, 0.61714513, 0.21565209],
        [0.11917814, 0.66547148, 0.89437986]]])

In [103]:
# high, low, shape, dtype
np.random.randint(-100, 100, (4, 5), dtype="int16")

array([[  4,   4,  86, -11, -74],
       [-70,  23,  57, -47, -44],
       [-48,  98, -51,  33, -27],
       [ 23, -89,  49, -79, -27]], dtype=int16)

In [104]:
# Identity matrix
np.identity(5, dtype="int32")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [105]:
# Repeat an existing array
a = np.array([1, 3, 6])
print(np.repeat(a, 3, axis=0))

# You need a to be a 2D array to repeat it in 2D
print(np.repeat([a], 3, axis=0))

# or
a = np.reshape(a, (1, -1))
print(np.repeat(a, 3, axis=0))

[1 1 1 3 3 3 6 6 6]
[[1 3 6]
 [1 3 6]
 [1 3 6]]
[[1 3 6]
 [1 3 6]
 [1 3 6]]


In [106]:
# Example: initialize the following array
# [[1, 1, 1, 1, 1],
#  [1, 0, 0, 0, 1],
#  [1, 0, 9, 0, 1],
#  [1, 0, 0, 0, 1],
#  [1, 1, 1, 1, 1]]

arr = np.ones((5, 5), dtype="int16")
arr[1:-1, 1:-1] = np.zeros((3, 3))
arr[2, 2] = 9
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

##### Be careful when copying arrays!!!

In [107]:
a = np.array([1, 2, 3])
b = a
b[0] = 100

print(a)

a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100

print(a)

[100   2   3]
[1 2 3]
