In [1]:
import numpy as np

# Reshape

In [2]:
a = np.arange(20)
print(a.reshape(2, 2, 5), "\n")

# You can have one unknown dimension as -1
print(a.reshape(-1, 5), "\n")
print(a.reshape(1, 1, 1, -1))

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]]]


## Flatten

In [3]:
b = np.arange(24).reshape(3, 4, -1).flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

You can also flatten column-wise
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html

## Transpose
Really useful if you wanna plot a graph and change columns to rows!

In [4]:
# for multidimentional array!
# Transpose essentially reshapes it with shape -> reverse order
# a = np.arange(30).reshape(2, 3, 5).transpose()
a = np.arange(18).reshape(6, 3).transpose()
a

array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])

# Roll & Swap axis
learn more abt this and update