In [1]:
import numpy as np

In [2]:
a = np.arange(9).reshape(3, 3)
b = np.arange(10, 13)
b

array([10, 11, 12])

----

In [3]:
np.add(a, b)

array([[10, 12, 14],
       [13, 15, 17],
       [16, 18, 20]])

In [4]:
np.multiply(a, b)

array([[ 0, 11, 24],
       [30, 44, 60],
       [60, 77, 96]])

In [5]:
np.subtract(a, b)

array([[-10, -10, -10],
       [ -7,  -7,  -7],
       [ -4,  -4,  -4]])

In [6]:
np.divide(a, b)

array([[0.        , 0.09090909, 0.16666667],
       [0.3       , 0.36363636, 0.41666667],
       [0.6       , 0.63636364, 0.66666667]])

----

In [7]:
a = np.arange(12).reshape(3, 4)
b = np.full((3, 4), 100)
b

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [8]:
np.add(a, b)

array([[100, 101, 102, 103],
       [104, 105, 106, 107],
       [108, 109, 110, 111]])