In [1]:
import numpy as np

----

## Iterating over entire array

In [2]:
a = np.arange(0, 45, 5).reshape(3, 3)

for i in a:
    print(i)

for i in np.nditer(a, order="F"):
    print(i)

# Order F -> column wise, Default -> C -> Row wise
# Or you can ofc flatten the aray and iterate through it the normal way

[ 0  5 10]
[15 20 25]
[30 35 40]
0
15
30
5
20
35
10
25
40


----
# Joining arrays
### Axis = 0

In [3]:
a = np.arange(1, 5).reshape(2, 2)
b = np.arange(5, 9).reshape(2, 2)

# While joining, note that all dimensions except
# the concatenation dimension must be equal in both the arrays

# Joining 2 arrays along axis 0
c = np.concatenate((a, b))
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

### Axis = 1

In [4]:
# Joining 2 arrays along axis 1
c = np.concatenate((a, b), axis=1)
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Axis = None

In [5]:
# Joining 2 arrays along axis None -> flattens arrays before joining
c = np.concatenate((a, b), axis=None)
c

array([1, 2, 3, 4, 5, 6, 7, 8])

### Axis = 0 (3d array)

In [6]:
a = np.arange(1, 5).reshape(1, 2, 2)
b = np.arange(5, 9).reshape(1, 2, 2)

# Joining 2 arrays along axis 0
c = np.concatenate((a, b))
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

----
# Spliting arrays
### Split by division

In [7]:
a = np.arange(10, 22)
np.split(a, 3)

[array([10, 11, 12, 13]), array([14, 15, 16, 17]), array([18, 19, 20, 21])]

### Split by position

In [8]:
np.split(a, [4, 7, 8])

[array([10, 11, 12, 13]),
 array([14, 15, 16]),
 array([17]),
 array([18, 19, 20, 21])]

----
# Resizing arrays

In [9]:
a = np.arange(1, 7).reshape(2, -1)
a

array([[1, 2, 3],
       [4, 5, 6]])

### Using resize as reshape

In [10]:
b = np.resize(a, (3, 2))
print(b)

[[1 2]
 [3 4]
 [5 6]]


### Using resize as resize lol

In [11]:
b = np.resize(a, (3, 5))
b

array([[1, 2, 3, 4, 5],
       [6, 1, 2, 3, 4],
       [5, 6, 1, 2, 3]])