In [1]:
import numpy as np

----

# 1. Create a 6x6 2d array
### Let 1 and 2 be placed alternatively across the diagonals
[1 0 1 0 1 0]<br>
[0 1 0 1 0 1]<br>
[1 0 1 0 1 0]<br>
[0 1 0 1 0 1]<br>
[1 0 1 0 1 0]<br>
[0 1 0 1 0 1]

In [2]:
a = np.zeros((6, 6), dtype="int16")

for i in range(6):
    for j in range(6):
        if (i + j) % 2 == 0:
            a[i][j] = 1

print(a)

[[1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]]


### Or

In [3]:
a = np.zeros((6, 6), dtype="int16")

a[::2, ::2] = 1
a[1::2, 1::2] = 1

print(a)

[[1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]]


----

# 2. Finding missing values
### Find the total number and locations of missing values in the array and replace it with a value

In [4]:
arr = np.random.rand(10, 10)
arr[np.random.randint(10, size=10), np.random.randint(10, size=10)] = np.nan
arr

array([[       nan, 0.61402648, 0.39517893,        nan, 0.73257323,
        0.50570177, 0.8370586 , 0.81796502, 0.77369727, 0.11896983],
       [0.52425921, 0.07914045, 0.5785616 , 0.94494122, 0.79614965,
        0.29301188, 0.27115731, 0.61027596, 0.65827811, 0.33448099],
       [0.45195996, 0.41242764, 0.90250908, 0.83318326,        nan,
        0.29385714, 0.11068442, 0.76036961, 0.74688562, 0.96928576],
       [0.15304987, 0.49389095, 0.79139233, 0.12417805, 0.62277468,
        0.0679467 , 0.87479832,        nan, 0.65981381, 0.78676383],
       [0.09704136, 0.54211027, 0.31944151, 0.30267702, 0.12770006,
        0.30784245, 0.95176022, 0.73324857, 0.89162335,        nan],
       [0.81184525, 0.23355112, 0.43230333, 0.96797106,        nan,
        0.92958137, 0.87552091, 0.99544532, 0.83901088, 0.51993832],
       [0.71586702, 0.02599416, 0.07449264, 0.0646214 , 0.41828511,
        0.22590567, 0.46008692, 0.17380274, 0.96412813, 0.50747793],
       [0.0948844 , 0.64172669, 0.9070348

In [5]:
np.isnan(arr).sum()

10

In [6]:
np.argwhere(np.isnan(arr))

array([[0, 0],
       [0, 3],
       [2, 4],
       [3, 7],
       [4, 9],
       [5, 4],
       [7, 9],
       [8, 3],
       [9, 3],
       [9, 8]])

In [7]:
index = np.where(np.isnan(arr))
arr[index] = "0"
arr

array([[0.        , 0.61402648, 0.39517893, 0.        , 0.73257323,
        0.50570177, 0.8370586 , 0.81796502, 0.77369727, 0.11896983],
       [0.52425921, 0.07914045, 0.5785616 , 0.94494122, 0.79614965,
        0.29301188, 0.27115731, 0.61027596, 0.65827811, 0.33448099],
       [0.45195996, 0.41242764, 0.90250908, 0.83318326, 0.        ,
        0.29385714, 0.11068442, 0.76036961, 0.74688562, 0.96928576],
       [0.15304987, 0.49389095, 0.79139233, 0.12417805, 0.62277468,
        0.0679467 , 0.87479832, 0.        , 0.65981381, 0.78676383],
       [0.09704136, 0.54211027, 0.31944151, 0.30267702, 0.12770006,
        0.30784245, 0.95176022, 0.73324857, 0.89162335, 0.        ],
       [0.81184525, 0.23355112, 0.43230333, 0.96797106, 0.        ,
        0.92958137, 0.87552091, 0.99544532, 0.83901088, 0.51993832],
       [0.71586702, 0.02599416, 0.07449264, 0.0646214 , 0.41828511,
        0.22590567, 0.46008692, 0.17380274, 0.96412813, 0.50747793],
       [0.0948844 , 0.64172669, 0.9070348

----