In [1]:
import numpy as np

### Linspace function
np.linspace(startindex, endindex, number_of_elements)

In [2]:
a = np.linspace(2, 5, 6)
a

array([2. , 2.6, 3.2, 3.8, 4.4, 5. ])

### Sum corresponding to axis

In [9]:
a = np.array([[[4, 5], [10, 10]], [[7, 8], [20, 5]]])
a.sum(axis=2)

array([[ 9, 20],
       [15, 25]])

### Sqrt and Std Deviation

In [13]:
a = np.arange(1, 10).reshape(3, 3)
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [14]:
np.std(a)

2.581988897471611

### Log

In [15]:
np.log10(a)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])