### Accessing and changing specific elements, rows, columns etc.

In [38]:
import numpy as np

In [39]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
a.shape

(2, 7)

In [40]:
# get a specific element [row, column]
print(a[1, 5])
a[1, -2]

13


13

In [41]:
# get a specific row and column
a[0, :]  # row
a[:, 2]  # column

array([ 3, 10])

In [42]:
# getting fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [43]:
# changing elements and rows and columns
a[0, :] = [20, 21, 22, 23, 24, 25, 26]  # change entire row
a[:, 0] = 100  # change entire column
a[1, 5] = 1000  # change element
a

array([[ 100,   21,   22,   23,   24,   25,   26],
       [ 100,    9,   10,   11,   12, 1000,   14]])

### 3D - example

In [44]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [45]:
# Get specific element - work outside in
b[1, 0, 1]

6

In [46]:
# Replace in 3D
b[:, 1, :] = [[10, 20], [30, 40]]
b

array([[[ 1,  2],
        [10, 20]],

       [[ 5,  6],
        [30, 40]]])